import "./globals.css";
import { ConfigProvider } from "antd";

export const metadata = {
  title: "Directory Admin Dash",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#467CC8", // Accent
              fontFamily: "Roboto, sans-serif",
            },
            components: {
              Layout: {
                headerBg: "#F5F5F5",
                bodyBg: "#F5F5F5",
              },
              Menu: {
                itemColor: "#F5F5F5", // normal state
                itemHoverColor: "#fff", // hover
                itemSelectedColor: "#6BA6FF", // selected
                itemBg: "transparent", // background
                itemSelectedBg: "#F5F5F5", // selected background
                subMenuItemBg: "transparent", // for nested items
                itemHeight: 32,
                fontSize: 18,
              },
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
